---
  # A note about permissions: the post-inst scripts for the riemann deb package
  # chown /etc/riemann to riemann:riemann recursively. Setting the same permissions
  # here rather than the more typical root:root 0644.
- name: Create configuration directory.
  file:
    path: "/etc/riemann/{{ item }}"
    state: directory
    owner: riemann
    group: riemann
    mode: "0755"
  with_items: "{{ riemann_create_folders }}"

- name: Copy over role default templates
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: riemann
    group: riemann
    mode: "0644"
  with_items: "{{ riemann_default_templates }}"
  notify: restart riemann

- name: Copy riemann.config
  copy:
    src: "{{ riemann_optional_baseconfig }}"
    dest: /etc/riemann/riemann.config
    owner: riemann
    group: riemann
    mode: "0644"
  when: "riemann_optional_baseconfig != ''"
  notify: restart riemann

- name: Copy additional configuration files
  copy:
    src: "{{ item }}"
    dest: "/etc/riemann/conf.d"
    owner: riemann
    group: riemann
    mode: "0644"
  with_fileglob: "{{ riemann_optional_addconfs }}"
  notify: restart riemann

- name: Copy additional clojure utility scripts
  copy:
    src: "{{ item }}"
    dest: /etc/riemann/utils/
    owner: riemann
    group: riemann
    mode: "0644"
  notify: restart riemann
  with_fileglob: "{{ riemann_optional_addutils }}"

- name: Copy hashmap variables
  template:
    src: config.clj.j2
    dest: /etc/riemann/vars/config.clj
    owner: riemann
    group: riemann
    mode: "0644"
  when: riemann_alerts_auth_map != {}
  notify: restart riemann
  tags: hashmap

- name: Start riemann service.
  service:
    name: riemann
    state: started
    enabled: yes
