---
- name: Install OpenJDK7.
  become: yes
  apt:
    name: openjdk-7-jre-headless
    state: present
  when: (ansible_distribution == "Debian")

- name: Install OpenJDK7.
  become: yes
  apt:
    name: openjdk-7-jre-headless
    state: present
  when: (ansible_distribution == "Ubuntu" and ansible_distribution_major_version <= "14")

- name: Install OpenJDK8.
  become: yes
  apt:
    name: openjdk-8-jre-headless
    state: present
  when: (ansible_distribution == "Ubuntu" and ansible_distribution_major_version >= "16")

- name: Download Riemann deb package.
  become: yes
  get_url:
    url: "{{ riemann_download_url }}"
    dest: "{{ riemann_deb_file_fullpath }}"
    owner: root
    group: root
    mode: "0644"

- name: Download Riemann checksum file.
  become: yes
  get_url:
    url: "{{ riemann_checksum_url }}"
    dest: "{{ riemann_checksum_fullpath }}"

  # If the get_url task didn't change, the checksum
  # won't be available in the registered var, so let's
  # reread the checksum every time.
- name: Read checksum for Riemann deb package.
  stat:
    path: "{{ riemann_deb_file_fullpath }}"
  register: riemann_download_checksum_result

- name: Validate checksum for deb package.
  command: cat {{ riemann_checksum_fullpath }}
  register: riemann_checksum_result
  changed_when: false
  failed_when: riemann_checksum_result.stdout !=
               "{{ riemann_download_checksum_result.stat.md5 }}  {{ riemann_deb_file_fullpath|basename }}"

- name: Install Riemann deb package.
  become: yes
  apt:
    deb: "{{ riemann_deb_file_fullpath }}"
    state: installed
  notify: restart riemann
